package com.exe.buddy_english_be.modules.character.controller;

import com.exe.buddy_english_be.modules.character.dto.CharacterTaskResponse;
import com.exe.buddy_english_be.modules.character.dto.GenerateCharacterRequest;
import com.exe.buddy_english_be.modules.character.service.CharacterService;
import com.exe.buddy_english_be.shared.response.ApiResponse;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/character")
@RequiredArgsConstructor
public class CharacterController {

    private final CharacterService characterService;

    /**
     * Submit a new Text-to-3D character generation request.
     * POST /api/character/generate
     */
    @PostMapping("/generate")
    public ResponseEntity<ApiResponse<CharacterTaskResponse>> generateCharacter(
            Authentication authentication,
            @Valid @RequestBody GenerateCharacterRequest request) {

        Long userId = (Long) authentication.getPrincipal();
        CharacterTaskResponse response = characterService.generateCharacter(userId, request);
        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(ApiResponse.success("Character generation task submitted", response));
    }

    /**
     * Poll the current status of a character task.
     * GET /api/character/task/{id}
     */
    @GetMapping("/task/{id}")
    public ResponseEntity<ApiResponse<CharacterTaskResponse>> getTaskStatus(
            Authentication authentication,
            @PathVariable Long id) {

        Long userId = (Long) authentication.getPrincipal();
        CharacterTaskResponse response = characterService.getTaskStatus(userId, id);
        return ResponseEntity.ok(ApiResponse.success("Task status fetched", response));
    }

    /**
     * Get all characters generated by the current user.
     * GET /api/character/my-characters
     */
    @GetMapping("/my-characters")
    public ResponseEntity<ApiResponse<List<CharacterTaskResponse>>> getMyCharacters(
            Authentication authentication) {

        Long userId = (Long) authentication.getPrincipal();
        List<CharacterTaskResponse> responses = characterService.getMyCharacters(userId);
        return ResponseEntity.ok(ApiResponse.success("Characters fetched successfully", responses));
    }
}
